name: dart_ipify
description: This package uses the remote ipify web services in order to get your public IP address or geographical details from any given IP.
version: 1.1.0
homepage: https://github.com/Bujupah/dart_ipify

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.6
  dotenv:
