name: dart_ipify
description: This package uses the remote ipify web services in order to get your public IP address or geographical details from any given IP.
version: 1.0.2
homepage: https://github.com/Bujupah/dart_ipify

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  http: ^0.12.2

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
